[package]
name = "challenge_6"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptopals = { path = "../../cryptopals" }
base64 = "0.13.0"
strided = "0.2.9"
